project/authentication/urls.py
from django.urls import include, path

from project.authentication import htmx_views, views

app_name = "auth"

htmx_urlpatterns = [
    path("check-email/", htmx_views.check_email, name="check-email"),
]

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("", include(htmx_urlpatterns)),
]

project/pages/urls.py
from django.urls import path

from project.pages import views

app_name = "pages"
urlpatterns = [path("", views.IndexPageView.as_view(), name="index")]

project/todos/urls.py
from django.urls import include, path

from project.todos import htmx_views, views

app_name = "todo"

htmx_urlpatterns = [
    path("add/", htmx_views.add_todo, name="add"),
    path("delete/<int:pk>/", htmx_views.delete_todo, name="delete"),
    path("search/", htmx_views.search_todo, name="search"),
    path(
        "toggle_is_done/<int:pk>",
        htmx_views.toggle_todo_is_done,
        name="toggle_is_done",
    ),
    path("sort/", htmx_views.sort_todos, name="sort"),
    path("edit_title/<int:pk>/", htmx_views.edit_todo_title, name="edit-title"),
]

urlpatterns = [
    path("list/", views.TodoListView.as_view(), name="list"),
    path("", include(htmx_urlpatterns)),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

from project.authentication.urls import urlpatterns as authentication_urls
from project.pages.urls import urlpatterns as pages_urls
from project.todos.urls import urlpatterns as todo_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include((authentication_urls, "auth"), namespace="auth")),
    path("todo/", include((todo_urls, "todo"), namespace="todo")),
    path("", include((pages_urls, "pages"), namespace="pages")),
    path("__debug__/", include("debug_toolbar.urls")),
]

project/authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _

from project.authentication.managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """User model that is used in this project. Email is the username field."""

    email = models.EmailField(_("Email Address"), unique=True)
    email_verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

project/pages/models.py
from django.db import models

# Create your models here.

project/todos/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _


class Todo(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name=_("Title"),
        blank=False,
        null=False,
    )
    is_done = models.BooleanField(
        blank=False,
        null=False,
        default=False,
        verbose_name=_("Is Done"),
    )
    due = models.DateField(blank=True, null=True, verbose_name=_("Due"))
    modification_time = models.DateTimeField(
        verbose_name=_("Modification Time"),
        auto_now=True,
    )
    order = models.PositiveIntegerField()
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name=_("User"),
    )

    class Meta:
        ordering = ["user", "order"]

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        # Get all todos with the same user and order greater than the current todo
        todos_to_update = Todo.objects.filter(user=self.user, order__gt=self.order)

        # Decrease the order of each todo by 1
        for todo in todos_to_update:
            todo.order -= 1
            todo.save()

        super().delete(*args, **kwargs)

project/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm

from project.authentication.models import User


class UserCreationForm(BaseUserCreationForm):
    class Meta:
        model = User
        fields = ("email",)

project/authentication/views.py
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    LogoutView as BaseLogoutView,
)
from django.views import generic
from django.urls import reverse_lazy

from project.authentication import forms as auth_forms


class LoginView(BaseLoginView):
    template_name = "accounts/login.html"


class SignUpView(generic.CreateView):
    form_class = auth_forms.UserCreationForm
    success_url = reverse_lazy("auth:login")
    template_name = "accounts/signup.html"

class LogoutView(BaseLogoutView):
    pass

project/pages/views.py
from django.views import generic


class IndexPageView(generic.TemplateView):
    template_name = "pages/index.html"

project/todos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from project.todos.models import Todo


class TodoListView(LoginRequiredMixin, generic.TemplateView):
    template_name = "todos/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_todos"] = Todo.objects.filter(user=self.request.user).order_by(
            "order",
            "is_done",
        )
        return context

project/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12 my-5">
            {% include "form_renderer.html" with form=form submit_button_text="Login" %}
        </div>
        <div class="col-12">
            Forgot your password? <a href="#">Reset your password.</a>
        </div>
        <div class="col-12">
            New here? <a href="#">Sign up</a> now.
        </div>
    </div>
</div>
{% endblock body %}

project/templates/accounts/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  Sign Up
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-12 my-5">
        <form method="POST">
          {% csrf_token %}

          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger mb-5" role="alert">{{ error }}</div>
            {% endfor %}
          {% elif form.errors %}
            <div class="alert alert-danger mb-5" role="alert">
              Please fix errors below to continue:<br /><br />
              {% for field, errors in form.errors.items %}
                <b>{{ field }}</b>:<ul>
                  {% for error in errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              {% endfor %}
            </div>
          {% endif %}

          <div class="mb-3">
            <div id="email-err"></div>
            {% render_field form.email|append_attr:"placeholder:Email" class='form-control' hx-post='/account/check-email/' hx-target='#email-err' hx-trigger='keyup delay:2s' %}
          </div>
          <div class="mb-3">
            {% render_field form.password1|append_attr:"placeholder:Password" class='form-control' %}
          </div>
          <div class="mb-3">
            {% render_field form.password2|append_attr:"placeholder:Password Repeat" class='form-control' %}
          </div>
          <input type="submit" class="btn btn-success" value="Sign Up" />
        </form>
      </div>
      <div class="col-12">
        You have an account? <a href="#">Login</a> now.
      </div>
    </div>
  </div>
{% endblock %}

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>
      {% block title %}
        Todo List
      {% endblock %}
    </title>
  </head>

  <body>
    {% block navbar %}
      {% include "partial/navbar.html" %}
    {% endblock %}
    {% block body %}

    {% endblock %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/htmx.js' %}"></script>
    <script src="{% static 'js/sortable.js' %}"></script>
    <script src="{% static 'js/response-targets.js' %}"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
    <script>
      htmx.onLoad(function(content) {
        var sortables = document.querySelectorAll(".sortable");
        for (var i = 0; i < sortables.length; i++) {
          var sortable = sortables[i];
          new Sortable(sortable, {
              animation: 150,
              ghostClass: 'blue-background-class'
          });
        }
      })
    </script>

  </body>
</html>

project/templates/form_renderer.html
<form method="POST">
  {% csrf_token %}

  {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger mb-5" role="alert">{{ error }}</div>
    {% endfor %}
  {% elif form.errors %}
    <div class="alert alert-danger mb-5" role="alert">
      Please fix errors below to continue:<br /><br />
      {% for field, errors in form.errors.items %}
        <b>{{ field }}</b>:<ul>
          {% for error in errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="mb-3">
      <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
      <input name="{{ field.html_name }}" type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" aria-describedby="emailHelp" />
      {% if field.help_message %}
        <div id="help" class="form-text">{{ field.help_message }}</div>
      {% endif %}
    </div>
  {% endfor %}
  <input type="submit" class="btn btn-success" value="{{ submit_button_text }}" />
</form>

project/templates/pages/index.html
{% extends "base.html" %}
{% block title %}Todo List{% endblock title %}
{% block navbar %}{% endblock navbar %}
{% block body %}
<header class="bg-primary text-white text-center py-5">
    <h1 class="display-4 font-merriweather">Welcome to <span class="font-italic fw-bold">Todo List</span></h1>
    <p class="lead font-roboto">The simple and efficient way to manage your tasks!</p>
</header>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Get Started</h2>
                    <p class="card-text">Start organizing your tasks and stay on top of your to-do list.</p>
                    {% if user.is_authenticated %}
                    <a href="{% url "todo:list" %}" class="btn btn-primary">Go to todo list</a>
                    {% else %}
                    <a href="{% url "auth:login" %}" class="btn btn-primary">Login</a>
                    <span class="mx-2">or</span>
                    <a href="{% url "auth:signup" %}" class="btn btn-primary">Sign up</a>

                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6 offset-md-3 my-2">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">More information about this project on <a href="https://github.com/thisisjab/todo_list_django">github.</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

project/templates/partial/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold fst-italic font-merriweather" href="{% url 'pages:index' %}">Taskinator</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'pages:index' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
              {{ user.email }}
            {% else %}
              Account
            {% endif %}
          </a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
              <li>
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
              </li>
            {% else %}
              <li>
                <a class="dropdown-item" href="{% url 'auth:login' %}">Login</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'auth:signup' %}">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

project/templates/todos/list.html
{% extends 'base.html' %}
{% block title %}
  Todos
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row my-5">
      <div class="col-12 mb-5">
        <form action="post" hx-on::after-request="this.reset()" hx-post="{% url 'todo:add' %}" hx-target="#todoList" hx-taget-400="">
          {% csrf_token %}
          <div class="row g-2">
            <div class="col-lg-8">
              <div class="form-floating">
                <input name="todo_title" type="text" class="form-control" id="todoTitle" placeholder="Bake cake for Jane's birthday" value="" />
                <label for="todoTitle">Add Todo</label>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-floating">
                <input name="todo_due" type="date" class="form-control" id="todoDue" />
                <label for="todoDue">Due</label>
              </div>
            </div>
            <div class="col-lg-2">
              <input type="submit" class="btn btn-success w-100 h-100" value="Add" />
            </div>
          </div>
        </form>
      </div>
      <hr>
      <div class="col-12 mb-3">
        <form method="post">
          <div class="input-group mb-1">
            <input hx-trigger="keyup delay:1s" hx-post="{% url "todo:search"  %}" hx-target="#todoList"  name="search_value" type="text" class="form-control" placeholder="Search..." aria-label="Search..." aria-describedby="btnSearch">
          </div>
        </form>
      </div>
      <hr>
      <div class="col-12" id="todoList">
        {% include "todos/partial/list.html" with user_todos=user_todos %}
      </div>
    </div>
  </div>
{% endblock %}

project/templates/todos/partial/list.html
{% if user_todos %}
  <form autocomplete="off" class="sortable list-group" hx-trigger="end" hx-post="{% url 'todo:sort' %}" hx-target="#todoList">
    {% for todo in user_todos %}
      {% include "todos/partial/todo_item.html" with todo=todo %}
    {% endfor %}
  </form>
{% else %}
  <p>You got no todos.</p>
{% endif %}

project/templates/todos/partial/todo_item.html
<div id="todo_item_{{ todo.pk }}">
  {% if todo.due %}
      <span class="badge text-bg-danger font-monospace" style="margin-left: 1rem; border-radius: 0;">Due: {{ todo.due|date:'c' }}</span>
  {% endif %}
  <input type="hidden" name="todo_orders" value="{{ todo.pk }}" />
  <li class="card d-flex flex-row align-items-center justify-content-between px-3 py-3 mb-3">
    {% if todo.is_done %}
      <input class="form-check-input" type="checkbox" name="is_done" id="" hx-get="{% url 'todo:toggle_is_done' todo.pk %}" hx-target="#todo_item_{{ todo.pk }}" checked />
      <p class="my-0 mx-3 text-body-tertiary">#{{ todo.order }}</p>
      <input type="text" class="form-control-no-focus my-0 text-decoration-line-through text-body-tertiary w-100 border-0" style="margin-right: 1rem;" value="{{ todo.title }}" />
      <div class="vr"></div>
      <span class="badge rounded-pill text-bg-danger" style="cursor: pointer; margin-left: 1rem" hx-delete="{% url 'todo:delete' todo.pk %}" hx-target="#todoList">X</span>
    {% else %}
      <input class="form-check-input" type="checkbox" name="is_done" id="" hx-get="{% url 'todo:toggle_is_done' todo.pk %}" hx-target="#todo_item_{{ todo.pk }}" />
      <p class="my-0 mx-3">#{{ todo.order }}</p>

      <input id="todo_{{ todo.pk }}_text" name="todo_title" class="form-control-no-focus my-0 w-100 border-0" style="margin-right: 1rem;" value="{{ todo.title }}" hx-post="{% url 'todo:edit-title' todo.pk %}" hx-target="#todo_{{ todo.pk }}_text" hx-target-400="" hx-trigger="keyup delay:500ms" />
      <div class="vr"></div>
      <span class="badge rounded-pill text-bg-danger" style="cursor: pointer; margin-left: 1rem;" hx-delete="{% url 'todo:delete' todo.pk %}" hx-target="#todoList">X</span>
    {% endif %}
  </li>
</div>